### ISSUE TITLE
Documentation migration

### ISSUE THREAD

**Issue by ohaucke** [ArthurHub/HTML-Renderer#100]
Hi,
i've done some work and migrated the documentation from codeplex to github.
You could find it under: https://github.com/ohaucke/HTML-Renderer/wiki
`git clone https://github.com/ohaucke/HTML-Renderer.wiki.git`

If you need help to merge this, feel free to contact me.

**Comment by ArthurHub** [comment]
Awesome! I have copied the wiki, thank you so much!

**Comment by ohaucke** [comment]
You are welcome.
Maybe you should consider to move this repo to an organization, so it would be easier to manage the permissions and open up another repository for the wiki it self to manage pull request and changes?

E.g.
TheArtOfDev / HTML-Renderer (main code)
TheArtOfDev / HTML-Renderer-Wiki (code for wiki)

In "HTML-Renderer-Wiki" we could maintain all changes for the wiki and even have the abibility for pull requests (which is a shame that github doesn't support it natively) and after a update on this repo happens someone send it to `https://github.com/ArthurHub/HTML-Renderer.wiki.git` or we could write a webhook to do this automaticly.
