### ISSUE TITLE
Can't set default text color

### ISSUE THREAD

**Issue by andrewpros** [ArthurHub/HTML-Renderer#135]
Hi.

There is no simple way to set the default text color, i use many wpf labels in my app.

The default value is hard coded here https://github.com/ArthurHub/HTML-Renderer/blob/cc3b5c221b192a950d3d53b561ac01049668e239/Source/HtmlRenderer/Core/Dom/CssBoxProperties.cs#L55

And it is black, the way the code works the only way to change it is to get access from CssBox, but not possible in controls. The css parser is not covering the default text style, probably cuz it is treating box model and html seriously, so if it is just plain text, there is NO TAGS = NO STYLE to set, setting a color style on body or '*' wont work.

This makes it impossible to use on dark UI as u cant change color to white.

The only workaround to make it work is to wrap every text used in controls in a span with class and then set its style in basestylesheet to work for all controls, but it is tedious.

There was also a suggestion almost 2 years ago  to make it happen using foreground color https://github.com/ArthurHub/HTML-Renderer/issues/55

@Licshee Is there any work being done?

Is this library even maintained anymore? Cuz if not, let me know, there is no point to even make a PR if it will not make it thru.

This is the best html wpf controls i have found so it is worth to keep it alive and fixing some issues.

**Comment by Symbai** [comment]
@andrewpros Did you found a workaround since you closed the issue? I got the same problem

**Comment by andrewpros** [comment]
@Symbai it was years ago, sorry i cant help u, but if its still not working after years and hard to do, just use other library

**Comment by Symbai** [comment]
For anyone having the same issue, I fixed it by simply surrounding the HTML I bind to Text property with html color tags. For example:

Instead of `Text="Blabla"` use changed it to `Text="<p style=\"color :red; \">Blabla</p>"`. You can also take a SolidColorBrush from resources and convert it to hex color string and use that instead of `red`.
