### ISSUE TITLE
English and digital fonts become empty.

### ISSUE THREAD

**Issue by yanjinhuagood** [ArthurHub/HTML-Renderer#136]
<p><span style="font-family:微软雅黑">9999</span></p>

![qq 20180810223931](https://user-images.githubusercontent.com/23089734/43963928-4a9147da-9cee-11e8-9994-03a28de2f4ab.png)

**Comment by yanjinhuagood** [comment]
“<p><span style="font-family:微软雅黑">000000000000</span></p>”

**Comment by yanjinhuagood** [comment]
![qq 20180810224532](https://user-images.githubusercontent.com/23089734/43964302-1a51519a-9cef-11e8-89bf-bf8a4869aaf1.png)

**Comment by hippasus** [comment]
you need to quote your font family as `font-family: '微软雅黑';`

**Comment by yanjinhuagood** [comment]
Thank you. You've been a great help already
