### ISSUE TITLE
Generated blank page - version: 1.5.1-beta1

### ISSUE THREAD

**Issue by therohlikar** [ArthurHub/HTML-Renderer#185]
Hey,

**PdfSharp**: 1.32.3057
**Html Renderer**: 1.5.1-beta1

Simple html code:
`<html><head></head><body>HELLO WORLD</body></html>`
but the renderer gives a blank page:

` pdfGenerated = "<html><head></head><body>HELLO WORLD</body></html>";`
                `PdfDocument pdf = new PdfDocument();`
                `pdf = PdfGenerator.GeneratePdf(pdfGenerated, PdfSharp.PageSize.A4);`
                `pdf.Save("notimportant.pdf");`

Any idea why?
Thanks,.

PS. earlier version works, but it cuts input in half in between the pages, so...

**Comment by ferry-aritonang** [comment]
Hi @therohlikar have you tried to use HtmlRenderer.PdfSharp with the same version [1.5.1-beta1](https://www.nuget.org/packages/HtmlRenderer.PdfSharp/1.5.1-beta1)?

**Comment by AndrewShchetkin** [comment]
Hi! I have the same issue. 
I use:
  HtmlRenderer.PdfSharp.1.5.1-beta1
  HtmlRenderer.Core.1.5.1-beta1
  PDFsharp.1.50.5147

**Comment by therohlikar** [comment]
> Hi @therohlikar have you tried to use HtmlRenderer.PdfSharp with the same version [1.5.1-beta1](https://www.nuget.org/packages/HtmlRenderer.PdfSharp/1.5.1-beta1)?

Hi, sorry for the late reply, it works now with these versions:

HtmlRenderer.Core: 1.5.1 beta1
HtmlRenderer.PdfSharp 1.5.1 beta1
PDFSharp 1.51.5185 beta

@AndrewShchetkin

**Comment by AndrewShchetkin** [comment]
Hi, @therohlikar!
I updated version PDFSharp to 1.51.5185 beta. But it is not worked for me.
I guess it's not work because I use styles for footer:
`
.footer {
  text-align:left;
  width:100%;
  position:fixed;
  left:20px;
  right:20px;
  bottom:20px;
  top:770px;
}`

If remove this styles, PdfGenerator generate right  PDF
