### ISSUE TITLE
Allow issue tracking on github

### ISSUE THREAD

**Issue by aggsol** [ArthurHub/HTML-Renderer#20]
Allowing issue tracking on github would allow easy tracking of issues, fixes and their corresponding pull requests or code changes.

**Comment by ArthurHub** [comment]
but the code plex site exist for a long time, contains wiki and discussions that are more likely to return in search...
Also I don't think its the right time to do so as I don't have the resources to commit fixing the issues.
make sence?

**Comment by aggsol** [comment]
Yeah, makes sense. I am going to create a codeplex account then. See you there.
