### ISSUE TITLE
html to pdf rendering, text getting clipped

### ISSUE THREAD

**Issue by sachithp** [ArthurHub/HTML-Renderer#45]
When a pdf is created from HTML, the text is not correctly rendered at the page break. The bottom line is clipped depending on the paragraph height hence reliable document rendering is an issue.

Preview of a pdf with clipped text.
![text_clipping_issue](https://cloud.githubusercontent.com/assets/4715345/16112114/95e37eaa-33d3-11e6-8a88-b23a3a1997cd.JPG)

**Comment by gyfke** [comment]
duplicates [this](https://github.com/ArthurHub/HTML-Renderer/issues/38)

The solution is [here](https://github.com/ArthurHub/HTML-Renderer/pull/41)
Notice that it requires prerelease version of PdfSharp and this changes are not included in nuget-package yet
