### ISSUE TITLE
Blurry text (WPF)

### ISSUE THREAD

**Issue by mythjuha** [ArthurHub/HTML-Renderer#53]
I'm trying to display basic html elements in a HTML Label. No html tag, body tag, or css style sheet. Just P, UL, LI elements. However, when shown on screen the text isn't sharp and is uncomfortale to read.

Any suggestions?

**Comment by jpomez** [comment]
Hi, 
It has been a while since you posted this issue, but if you are still interested, I made a PR that fixes it (at least in my use cases) here: #62. 
I would be glad tho have your feedback if the fix works (or not) for you.

Thanks.

**Comment by Licshee** [comment]
This should be fixed by #62.
Feel free to reopen if you still encounter the same problem.

**Comment by swdriessen** [comment]
I was looking into why my text was blurry at some points (including the demo app), un-doing these changes actually greatly decreases the blurryness for me. Even the html popup is now crisp clear.

I will test it on multiple machines and scaling this week, but for me this is what makes things blurry.
(I'm on 100% scaling)

(demo app: a before (current), and after(commenting the changes made in this PR))

![before](https://user-images.githubusercontent.com/1596388/27603634-ed2e1e74-5b76-11e7-8186-b2dbf421aa9e.png)
![after](https://user-images.githubusercontent.com/1596388/27603638-ef675688-5b76-11e7-8adc-49de4bd0d09a.png)

**Comment by jpomez** [comment]
Hi,

Sorry to read that... could you provide the resolution you are using ? We may have to take the DPI in account...

In my use case, the PR fixed the problem on full hd screens with 100% scaling. Unfortunately I don't have the hardware to perform testing on other resolutions.

Thanks in advance for your help.

**Comment by swdriessen** [comment]
I'm also on a 1920*1080 at 100%, same result on my 2nd monitor which is a smaller one 1440*900.

**Comment by RachamimYaakobov** [comment]
I have a 1920x1080 screen at 125% and the text is very blurry
What to do?
