### ISSUE TITLE
Can add Lib HTML-Renderer to services ?

### ISSUE THREAD

**Issue by tinamore** [ArthurHub/HTML-Renderer#58]
Hi
Thanks you for project. I have a error when add lib to my project "windows services"
```
An unhandled exception of type 'System.IO.FileLoadException' occurred in mscorlib.dll

Additional information: Could not load file or assembly 'HtmlRenderer, Version=1.5.0.6, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
```
how to fix it? Thanks.

**Comment by Licshee** [comment]
Do you still have the same problem?
The error message sounds like you didn't place the assembly of HTML-Renderer in a place where your service process can find.

**Comment by Licshee** [comment]
Please reopen if you still need this to be fixed
