### ISSUE TITLE
Interested in continue supporting for this project

### ISSUE THREAD

**Issue by Licshee** [ArthurHub/HTML-Renderer#70]
First of all, thank you for the great job you have done!
Me and a several friends definitely need pure managed HTML rendering engine, that's why we looked into this.
What requirements do you want us to meet?

**Comment by rkarina** [comment]
A main issue for me is Line Height/Line Spacing. The PDF converter doesn't seem to cater for point values and/or integer values (e.g. line-height: 12pt and line-height: 1).

**Comment by rkarina** [comment]
Another recurring issue I've seen in the discussion/issues section is issues with in-line styling and the style sheet tag in the HTML string when converting to PDF.

**Comment by PawelMaj** [comment]
Try to get in contact with Arthur regarding this. I was able to email him through the nuget package page, i think. Unfortunately I am just helping a tiny bit with Nuget management. In the end it is his project so it is up to him to give you permission to contribute. I do not want to share his contact info without his permission, sorry.

**Comment by Licshee** [comment]
@PawelMaj no worry, that's why I open this issue

**Comment by Jedarc** [comment]
+1
I am a .Net developer, I started using the library on a project, and I would like to contribute as well.

**Comment by ArthurHub** [comment]
Sorry for slow response, I'm on a ski vecation :)
I have no requirements, if you are willing and have the time that's all
that matters!
Will be back next week, send me an email with some more details and we will
take it from there.
Thanks!

**Comment by Licshee** [comment]
okay

**Comment by Licshee** [comment]
I think it's safe to close this for now.
