### ISSUE TITLE
GTK# control

### ISSUE THREAD

**Issue by kedrin** [ArthurHub/HTML-Renderer#76]
Would/has anyone written a GTK# control for this?

**Comment by ArthurHub** [comment]
GTK?

**Comment by kedrin** [comment]
http://www.mono-project.com/docs/gui/gtksharp/

**Comment by ArthurHub** [comment]
There is no support for it at the moment and I don't see it getting priority.
If you want to contribute I think it will be relatively easy to do and you can look on how mono is implemented for reference.

**Comment by kedrin** [comment]
Love to but writing my own control is well above my head currently. I may try tho.
