### ISSUE TITLE
Exception: Could not load file or assembly 'HtmlRenderer, version=1.5.0.5'

### ISSUE THREAD

**Issue by ferpega** [ArthurHub/HTML-Renderer#77]
Hello, 

I am trying to convert html from a mail-body into PDF.

I have this code:

```
using PdfSharp;
using System;
using System.IO;
using TheArtOfDev.HtmlRenderer.PdfSharp;

namespace myNamespace.Services.Pdf
{
    public class PdfCreator : IPdfCreator
    {
        public byte[] CreateFromHtml(string bodyOriginal)
        {
            if (string.IsNullOrEmpty(bodyOriginal))
                return null;

            try
            {
                using (var outputStream = new MemoryStream())
                {
                    var pdf = PdfGenerator.GeneratePdf(bodyOriginal, PageSize.A4);
                    pdf.Save(outputStream);
                    var result = outputStream.ToArray();
                    pdf.Dispose();
                    return result;
                }               
            }
            catch (Exception ex)
            {
                return null;
            }
        }
    }
}
```

But always I call this CreateFromHtml function I got an exception:

> Could not load file or assembly 'HtmlRenderer, Version=1.5.0.5, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

I am working with net framework 4.6.1 and I have installed HtmlRenderer with Nuget package.

I have tested the htmlrenderer.dll is in the bin folder.

Any help would be appreciated.

**Comment by ferpega** [comment]
Solved.

I have forget to add the nuget package reference to the mail console program app was calling the library with the transformation code.

Sorry.

**Comment by ruchikaperera** [comment]
I get the same error, what is the solution ?

**Comment by pedrotomaz** [comment]
Check the versions installed by nuget and upgrade to the latest versions.

**Comment by burakdgn9** [comment]
HtmlRenderer.PdfSharp v1.5.0.6 is loaded as HtmlRenderer.Core v1.5.0.5. Update HtmlRenderer.Core version to v1.5.0.6.

**Comment by CoderVivekHub** [comment]
I still get below error. I update to latest version v1.5.0.6: 

System.IO.FileNotFoundException: 'Could not load file or assembly 'HtmlRenderer, Version=1.5.0.6, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.'

**Comment by dnsnx** [comment]
Same issue here. Blank project (Console App / .NET8) / Version 1.5.0.6

> System.IO.FileNotFoundException: 'Could not load file or assembly 'HtmlRenderer, Version=1.5.0.6, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.'

**Comment by daemon29** [comment]
Clean solution, reinstall the 2 packages: htmlrenderer.Core and htmlrendere.pdfsharp, and build the solution again.

**Comment by m4ert** [comment]
Yep... it's 2025 and the issue still persists.

I solved it by downgrading the `HtmlRenderer.PdfSharp` library to version `1.5.0.5`.
