### ISSUE TITLE
unable to combine bold with italic

### ISSUE THREAD

**Issue by swdriessen** [ArthurHub/HTML-Renderer#83]
Hello,

I can't seem to combine bold and italic with inline styles or css. Anyone got a fix for this issue?

It also doesn't work in the demo application and there isn't any sample in there that applies it.

**Comment by Licshee** [comment]
will check soon

**Comment by Licshee** [comment]
Sorry, something happened, I'm not sure how long would it take before I can examine into this.

**Comment by swdriessen** [comment]
Thanks anyway.

I found it grabs the weight and style and seems to get the proper font but then just renders it normal.

(i should add it's for WPF)
